# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='duration',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
